image: node

build:
  stage: build

  artifacts:
    name: "alwaysontop_0.1.0_amd64.deb"
    when: always
    expire_in: never
    paths:
      - ./dist/installers/

  script:
    - npm install
    - npm install -g electron-installer-debian
    - npm run linux64
    - npm run deb64
