image: node

build:
  stage: build

  artifacts:
    name: "alwaysontop.snap"
    when: always
    expire_in: never
    paths:
      - ./

  script:
    - mkdir /bin/bash
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - brew install fakeroot dpkg
    - yarn install
    - yarn linux64
    - yarn deb64
