image: node

build:
  stage: build

  artifacts:
    name: "alwaysontop_0.1.0_amd64.deb"
    when: always
    expire_in: never
    paths:
      - ./dist/installers/

  script:
    - git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
    - mkdir ~/.linuxbrew/bin
    - ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
    - eval $(~/.linuxbrew/bin/brew shellenv)
    - brew install fakeroot
    - yarn install
    - yarn linux64
    - yarn deb64
