image: node

build:
  stage: build

  artifacts:
    name: "alwaysontop_0.1.0"
    when: always
    expire_in: never
    paths:
      - ./alwaysontop-linux-x64/alwaysontop

  script:
    - yarn install
    - yarn linux64
    - DEB_BUILD_OPTIONS="parallel=4" fakeroot debian/rules binary
    - yarn deb64
