image: node

build:
  stage: build

  artifacts:
    name: "alwaysontop_0.1.0_amd64.deb"
    when: always
    expire_in: never
    paths:
      - ./dist/installers/

  script:
    - yarn install
    - yarn linux64
    - apt-get install fakeroot
    - yarn deb64
