image: node

build:
  stage: build

  artifacts:
    name: "alwaysontop.snap"
    when: always
    expire_in: never
    paths:
      - ./out

  script:
    - apt update
    - apt install snapd -y
    - snap install hello-world
    - hello-world
    - yarn install
    - yarn build:package && yarn build:snap
