image: node

build:
  stage: build

  artifacts:
    name: "alwaysontop.snap"
    when: always
    expire_in: never
    paths:
      - ./out/alwaysontop-linux-x64

  script:
    - sudo apt update
    - sudo apt install snapd
    - sudo snap install hello-world
    - hello-world
    - yarn install
    - yarn build:package && yarn build:snap
